services:
  dockge:
    image: louislam/dockge:1
    container_name: phantom_dockge
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - ./stacks:/app/data/stacks
    environment:
      - DOCKGE_STACKS_DIR=/app/data/stacks
