services:
  i2pd:
    image: purplei2p/i2pd:latest
    container_name: phantom_i2pd
    restart: unless-stopped
    command:
      - "--http.address=0.0.0.0"
      - "--http.strictheaders=false"
      - "--httpproxy.address=0.0.0.0"
      - "--socksproxy.address=0.0.0.0"
    ports:
      - "7070:7070"
      - "4444:4444"
      - "4447:4447"
    volumes:
      - ./data:/var/lib/i2pd
