server:
    verbosity: 1
    interface: 0.0.0.0
    port: 53
    do-ip4: yes
    do-udp: yes
    do-tcp: yes
    do-ip6: no
    prefer-ip6: no

    # Hide DNS Server version and identity
    hide-identity: yes
    hide-version: yes

    # Trust anchor file, used for DNSSEC validation
    auto-trust-anchor-file: "/opt/unbound/etc/unbound/var/root.key"

    # Harden against cache poisoning
    harden-glue: yes
    harden-dnssec-stripped: yes
    use-caps-for-id: no
    edns-buffer-size: 1232
    prefetch: yes
    num-threads: 1

    # Access control
    access-control: 127.0.0.1/32 allow
    access-control: 172.29.0.0/24 allow
