version: '3.8'

services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: phantom_rustdesk_hbbs
    command: hbbs -r 127.0.0.1:21117
    restart: unless-stopped
    ports:
      - "127.0.0.1:21115:21115"
      - "127.0.0.1:21116:21116"
      - "127.0.0.1:21116:21116/udp"
      - "127.0.0.1:21118:21118"
    volumes:
      - ./data:/root
    depends_on:
      - hbbr

  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: phantom_rustdesk_hbbr
    command: hbbr
    restart: unless-stopped
    ports:
      - "127.0.0.1:21117:21117"
      - "127.0.0.1:21119:21119"
    volumes:
      - ./data:/root
